<a href="https://colab.research.google.com/github/ashii18/ann/blob/main/ann4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:


import numpy as np
import random
import math

X1 = [1, 1, 1, 1, 1, 1]
X2 = [-1, -1, -1, -1, -1, -1]
X3 = [1, -1, -1, 1, 1, 1]
X4 =[1, 1, -1, -1, -1, -1]
X = np.array([X1, X2, X3, X4])

Y1 = [1, 1, 1]
Y2 =[-1, -1, -1]
Y3 = [-1, 1, 1]
Y4 = [1, -1, 1]
Y = np.array([Y1, Y2, Y3, Y4])

print("X = ", X)
print("\nY = ", Y)
print("\n\nDimensions of X: ", X.shape)
print("\nDimensions of Y: ", Y.shape)

X =  [[ 1  1  1  1  1  1]
 [-1 -1 -1 -1 -1 -1]
 [ 1 -1 -1  1  1  1]
 [ 1  1 -1 -1 -1 -1]]

Y =  [[ 1  1  1]
 [-1 -1 -1]
 [-1  1  1]
 [ 1 -1  1]]


Dimensions of X:  (4, 6)

Dimensions of Y:  (4, 3)


In [6]:
def calcweight (X, Y):
  return np.dot(X.T, Y)
weight= calcweight (X, Y)
print('W =', weight, end = "")

print("\n\nDimensions of Weight Matrix: ",weight.shape)

W = [[2 2 4]
 [4 0 2]
 [2 2 0]
 [0 4 2]
 [0 4 2]
 [0 4 2]]

Dimensions of Weight Matrix:  (6, 3)


In [7]:

def ForwardBipolarActivation (matrix, weight):
  matrix[matrix > 0] = 1
  matrix[matrix <= 0]=-1
  return np.array(matrix)

def BackwardBipolarActivation (matrix, weight):
  matrix[matrix >= 0] = 1
  matrix[matrix < 0] = -1
  return np.array(matrix)

def forward (Y, weight):
  x = np.dot (Y, weight.T)
  return ForwardBipolarActivation (x, weight)


print("\nweight Y1 = ", forward (Y1, weight)," = x1")
print("\nweight Y2 = ", forward (Y2, weight), " = x2")
print("\nweight * Y3 = ", forward (Y3, weight), " = x3")
print("\nweight Y4 = ", forward (Y4, weight), " = x4")
print("\n\nIt is observed that the obtained results match with the original x matrices. \n\nThus forward testing is 100% accurate.")



weight Y1 =  [1 1 1 1 1 1]  = x1

weight Y2 =  [-1 -1 -1 -1 -1 -1]  = x2

weight * Y3 =  [ 1 -1 -1  1  1  1]  = x3

weight Y4 =  [ 1  1 -1 -1 -1 -1]  = x4


It is observed that the obtained results match with the original x matrices. 

Thus forward testing is 100% accurate.


In [8]:
def backward (X, weight):
  Y = np.dot (weight.T, X)
  return BackwardBipolarActivation (Y, weight)


print("\nweight x1 = ", backward (X1, weight),"= Y1")
print("\nweight X2 =", backward (X2, weight), " = Y2")
print("\nweight x3 = ", backward (X3, weight), " = Y3")
print("\nweight x4 = ", backward (X4, weight), " = Y4")
print("\n\nIt is observed that the obtained results match with the original Y (target) matrices. \n\nThus backward testing is 100% accurate.")


weight x1 =  [1 1 1] = Y1

weight X2 = [-1 -1 -1]  = Y2

weight x3 =  [-1  1  1]  = Y3

weight x4 =  [ 1 -1  1]  = Y4


It is observed that the obtained results match with the original Y (target) matrices. 

Thus backward testing is 100% accurate.
